export const SOUNDS = {
  start: "./sounds/rnd1.mp3",
  fight: "./sounds/fight.mp3",
  draw: "./sounds/draw/mk3-09195.mp3",
  hits: [
    "./sounds/hits/mk3-00100.mp3",
    "./sounds/hits/mk3-00120.mp3",
    "./sounds/hits/mk3-00125.mp3",
    "./sounds/hits/mk3-00275.mp3",
    "./sounds/hits/mk3-00355.mp3",
    "./sounds/hits/mk3-00190.mp3",
    "./sounds/hits/mk3-00215.mp3",
  ],
  block: "./sounds/block/mk3-00175.mp3",
  arenas: [
    "./sounds/arenas/mk3-00006.mp3",
    "./sounds/arenas/mk3-00010.mp3",
    "./sounds/arenas/mk3-00014.mp3",
    "./sounds/arenas/mk3-00018.mp3",
    "./sounds/arenas/mk3-00021.mp3",
    "./sounds/arenas/mk3-00026.mp3",
    "./sounds/arenas/mk3-00034.mp3",
    "./sounds/arenas/mk3-00046.mp3",
  ],
  lose: [
    "./sounds/lose/mk3-09440.mp3",
    "./sounds/lose/mk3-09450.mp3",
    "./sounds/lose/mk3-09455.mp3",
  ],
  victory: [
    "./sounds/victory/mk3-09125.mp3",
    "./sounds/victory/mk3-09130.mp3",
    "./sounds/victory/mk3-09135.mp3",
  ],
  names: {
    "rain": "./sounds/names/rain.mp3",
    "reptile": "./sounds/names/reptile.mp3",
    "stryker": "./sounds/names/stryker.mp3",
    "jax": "./sounds/names/jax.mp3",
    "night wolf": "./sounds/names/nightwolf.mp3",
    "jade": "./sounds/names/jade.mp3",
    "noob saibot": "./sounds/names/noobsaibot.mp3",
    "sonya": "./sounds/names/sonya.mp3",
    "kano": "./sounds/names/kano.mp3",
    "mileena": "./sounds/names/mileena.mp3",
    "sub-zero": "./sounds/names/subzero.mp3",
    "kung lao": "./sounds/names/kunglao.mp3",
    "sektor": "./sounds/names/sektor.mp3",
    "kitana": "./sounds/names/kitana.mp3",
    "ermac": "./sounds/names/ermac.mp3",
    "scorpion": "./sounds/names/scorpion.mp3",
    "cyrax": "./sounds/names/cyrax.mp3",
    "kabal": "./sounds/names/kabal.mp3",
    "sindel": "./sounds/names/sindel.mp3",
    "smoke": "./sounds/names/smoke.mp3",
    "liu kang": "./sounds/names/liukang.mp3",
    "shang tsung": "./sounds/names/shangtsung.mp3",
  },
}